# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nginx:
  replicaCount: 2
  image:
    repo: hwchiu/hiskio-gitops
    tag: 4439d34
  pullPolicy: Always
  prefix: hook-demo-again
hook: true
