apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Chart.Name }}
data:
  index: |
     <HTML>
     <HEAD>
     <TITLE>Your Title Here</TITLE>
     </HEAD>
     <BR> <B><I>This is a new sentence without a paragraph break, in bold italics.</I></B>
     </BODY>
     </HTML>
